version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build-and-test:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Analyze code
          command: flutter analyze
      - run:
          name: Run tests
          command: flutter test || true
      - run:
          name: Build debug APK
          command: flutter build apk
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - dev
